{
  # Robotic system description and bag file info. You can use an Uniform Resource Identifier (URI) string or a local path.
  # Know schemas: [file, package]. The package is for designating a ros package such as the calibration_pkg the example
  # bellow.
  #    Example 1: file:///home/mike/catkin_ws/src/calibration_pkg/urdf/description.xacro
  #    Example 2: package://calibration_pkg/urdf/description.xacro
  # It is also possible to put in just a path,
  #    Example 3: /home/mike/catkin_ws/src/calibration_pkg/urdf/description.xacro
  # and to include common path symbols (~) or environment variables
  #    Example 4: ~/catkin_ws/src/calibration_pkg/urdf/description.xacro
  #    Example 5: /home/$(USER)/catkin_ws/src/calibration_pkg/urdf/description.xacro
  # This is valid for description_file, bag_file and calibration_pattern/mesh_file
  "description_file": "package://atlascar2_description/urdf/atlascar2.urdf.xacro",
  "bag_file": "$ROS_BAGS/atlascar2/calibration_5_dez_2019_03m-07m.bag",
#  "description_file": "http:///home/mike/catkin_ws/src/calibration/atlascar2/atlascar2_description/urdf/atlascar2.urdf.xacro",
#  "bag_file": "~/bagfiles/calibration_5_dez_2019_03m-07m.bag",

   # Specify all sensors that are used in the calibration: Each sensor should have:
   # <sensor_name>: {"link": <The frame of the sensor's data. The value of the sensor's message.header.frame_id.>,
   #                 "parent_link": <Parent frame of the transformation to be calibrated.>,
   #                 "child_link" : <Child frame of the transformation to be calibrated.>,
   #                 "topic_name" : <Name of the ros message topic that contains this sensor's data.>
   #                }
   #
    "sensors": {
        # Examples
         "left_laser": {
                "link": "left_laser",
                "parent_link": "base_link",
                "child_link": "left_laser",
                "topic_name": "/left_laser/laserscan"
        },
         "right_laser": {
           "link": "right_laser",
           "parent_link": "base_link",
           "child_link": "right_laser",
           "topic_name": "/right_laser/laserscan"
         },
        "top_left_camera": {
                "link": "top_left_camera_optical",
                "parent_link": "base_link",
                "child_link": "top_left_camera",
                "topic_name": "/top_left_camera/image_color"
        },
        "top_right_camera": {
                "link": "top_right_camera_optical",
                "parent_link": "base_link",
                "child_link": "top_right_camera",
                "topic_name": "/top_right_camera/image_color"
        },
#        "top_center_rgbd_camera_rgb": {
#           "link": "top_center_rgbd_camera_rgb_optical_frame",
#           "parent_link": "base_link",
#           "child_link": "top_center_rgbd_camera_link",
#           "topic_name": "/top_center_rgbd_camera/rgb/image_raw"
#         }
    },

    # This section describes the properties of the calibration pattern used
    # for calibration.
    "calibration_pattern" : {
        # The frame id (or link) of the pattern.
        # This link transformation will be optimized.
        "link": "chessboard_link",
        # The parent frame id (or link) of the pattern.
        # For example, in hand-eye calibration the parent link
        # of the pattern can be the end-effector or the base of the arm
        "parent_link": "base_link",
        # Defines if the pattern link is the same in all collections (i.e. fixed=true),
        # or each collection will have its own estimative of the link transformation.
        "fixed": false,
        # The type of pattern used for the calibration.
        # Suported pattern are:
        # - chessboard
        # - charuco
        "pattern_type": "chessboard",
        # If the pattern type is "charuco" you need to define
        # the aruco dictionary used by the pattern.
        # See https://docs.opencv.org/trunk/dc/df7/dictionary_8hpp.html
        "dictionary": "DICT_5X5_100",
        # Mesh file (collada.dae or stl) for showing pattern on rviz. URI or regular path. See above description_file.
        # Leave empty ("") if there is no mesh file.
        "mesh_file": "",
        # The border width from the edge corner to the pattern physical edge.
        # This is used for 3D sensors and lidars.
        "border_size": 0.5,
        # The number of corners the pattern has in the X and Y dimentions.
        # Note: The charuco detector uses the number of squares per dimension in
        # its detector. Internally we add a +1 to Y and X dimensions to account for
        # that. Therfore, the number of corners should be used even for the charuco
        # pattern.
        "dimension": {"x": 9, "y": 6},
        # The length of the a square edge.
        "size": 0.101,
        # The length of the charuco inner marker.
        "inner_size": 0.014
    },

    # Miscellaneous information
    "anchored_sensor": "top_left_camera",     # Anchor a given sensor, making it immovable during the optimization.
    "world_link": "base_link",             # Frame of reference for the optimization procedure. Must exist in the
                                           # transformation chains of all the sensors which are being calibrated.
    "max_duration_between_msgs": 1  # Max time delta between sensor data messages when creating a collection.
}
